config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :attendances do
    get :previous_timestamp
  end
  resources :messages, only: :show
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  has_many :messages, through: :attendances
  has_many :received_messages, class_name: 'Message', foreign_key: 'receiver_id', dependent: :destroy
  has_secure_password

  attr_accessor :remember_token
  validates :name, presence: true, length: { maximum: 50 }
  validates :employee_number, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  class << self
    # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end

    def ransackable_attributes(auth_object = nil)
      ["admin", "created_at", "employee_number", "id", "name", "password_digest", "remember_digest", "updated_at", "timestamp"]
    end

    def ransackable_associations(auth_object = nil)
      ["attendances", "messages", "received_messages"]
    end
  end

  # 永続的セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  # セッションハイジャック防止のためにセッショントークンを返す
  # この記憶ダイジェストを再利用しているのは単に利便性のため
  def session_token
    remember_digest || remember
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :admin_user

  def new
    @user = User.new
  end

  def index
    @search = User.ransack(params[:q])
    @users = Kaminari.paginate_array(@search.result).page(params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "正常に追加されました。"
      redirect_to users_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "正常に更新されました。"
      redirect_to users_path
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:success] = "正常に削除しました"
      redirect_to users_path
    else
      redirect_to users_path, :unprocessable_entity
    end
  end

  private
  
    def user_params
      params.require(:user).permit(:name, :employee_number, :password, :password_confirmation)
    end

    #before_action
    def admin_user
      redirect_to(root_url, status: :see_other) unless current_user&.admin?
    end
end

app/views/users/_form.html.erb
<div class="signin_form">
  <%= bootstrap_form_with(model: @user, local: true) do |f| %>
    <%= f.text_field :name, label: "氏名" %>
    <%= f.text_field :employee_number, label: "社員番号" %>
    <%= f.password_field :password, label: "パスワード" %>
    <%= f.password_field :password_confirmation, label: "パスワード確認" %>
    <%= f.submit yield(:button_text), class: "signin_button" %>
  <% end %>
</div>

app/views/users/_user.html.erb
<th><%= user.employee_number %></th>
<th><%= user.name %></th>
<th>
  <% if user.attendances.where(status: "begin")&.last %>
    <%= user.attendances.where(status: "begin").last.timestamp.strftime("%m月%d日 %H:%M") %>
  <% end %>
  ~
  <% if user.attendances.where(status: "finish")&.last %>
    <%= user.attendances.where(status: "finish").last.timestamp.strftime("%m月%d日 %H:%M") %>
  <% end %>
</th>

<% if user.attendances&.where(status: "modification_request")&.first %>
  <th>
    <%= user.attendances.where(status: "modification_request").first&.message&.attendance_to_change&.timestamp&.strftime("%m月%d日 %H:%M") %>
    (<%= user.attendances.where(status: "modification_request").first&.message&.attendance_to_change&.status_to_japanese %>)
    →<%= user.attendances.where(status: "modification_request").first&.timestamp&.strftime("%m月%d日 %H:%M") %>
  </th>
  <th>
    <%= user.attendances.where(status: "modification_request").first&.message&.content %>
  </th>
<% else %>
  <th></th>
  <th></th>
<% end %>

<th><%= link_to "詳細", user_path(user), class: "button" %></th>
<th><%= link_to "社員情報変更", edit_user_path(user), class: "button" %></th>
<th>
    <%= link_to "社員情報削除", user, class: "button", data: { turbo_method: :delete,
                                          turbo_confirm: "本当に削除しますか" } %>
</th>

app/views/users/edit.html.erb
<% provide(:title, '社員情報変更') %>
<% provide(:button_text, '変更') %>

<%= link_to new_user_path, class: "new_link" do %>
  <%= image_tag "signin.svg" %>
  新規登録
<% end %>
<%= link_to "出勤一覧",attendances_path, class: "button right" %>
<%= link_to "社員一覧", users_path, class: "button right low" %>

<h1>社員情報変更</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<% provide(:title, '社員一覧') %>
<%= link_to new_user_path, class: "new_link" do %>
  <%= image_tag "signin.svg" %>
  新規登録
<% end %>
<%= link_to "出勤一覧", attendances_path, class: "button right" %>
<%= link_to "出勤登録", new_attendance_path, class: "button right low" %>

<%= search_form_for @search, html: { data: { turbo_frame: "users-list" } } do |f| %>
  <% if params[:q] %>
    <%= f.label :name_cont, "氏名で調べる" %>
    <%= f.search_field :name_cont, placeholder: "氏名を入力", value: params[:q][:name_cont] %>
    <%= f.hidden_field :attendances_status_eq, value: "begin" %>
    <%= f.label :attendances_timestamp_gteq, "出勤日で調べる" %>
    <div class="date_range">
      <%= f.date_field :attendances_timestamp_gteq, value: params[:q][:attendances_timestamp_gteq] %>
      〜
      <%= f.date_field :attendances_timestamp_lteq_end_of_day, value: params[:q][:attendances_timestamp_lteq_end_of_day] %>
    </div>
  <% else %>
    <%= f.label :name_cont, "氏名で調べる" %>
    <%= f.search_field :name_cont, placeholder: "氏名を入力" %>
    <%= f.hidden_field :attendances_status_eq, value: "begin" %>
    <%= f.label :attendances_timestamp_gteq, "出勤日で調べる" %>
    <div class="date_range">
      <%= f.date_field :attendances_timestamp_gteq %>
      〜
      <%= f.date_field :attendances_timestamp_lteq_end_of_day %>
    </div>
  <% end %>
  <%= f.submit %>
  <%= link_to "クリア", users_path, class: "button" %>
<% end %>

<table id="users">
  <tr>
    <th>社員番号</th>
    <th>社員名</th>
    <th>出勤時間~退勤時間(直近)</th>
    <th>修正依頼(直近)</th>
    <th>修正依頼理由</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <%= render user %>
    </tr>
  <% end %>
</table>

<%= paginate @users %>

app/views/users/new.html.erb
<% provide(:title, '社員新規登録') %>
<% provide(:button_text, '新規登録') %>

<%= link_to new_user_path, class: "new_link" do %>
  <%= image_tag "signin.svg" %>
  新規登録
<% end %>
<%= link_to "出勤一覧",attendances_path, class: "button right" %>
<%= link_to "社員一覧", users_path, class: "button right low" %>

<h1>社員新規登録</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<%= link_to new_user_path, class: "new_link" do %>
  <%= image_tag "signin.svg" %>
  新規登録
<% end %>
<%= link_to "出勤一覧",attendances_path, class: "button right" %>
<%= link_to "社員一覧", users_path, class: "button right low" %>

<%= @user.name %>さん