config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :attendances do
    get :previous_timestamp
  end
  resources :messages, only: :show
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  has_one :message, class_name: 'Message', dependent: :destroy
  accepts_nested_attributes_for :message
  belongs_to :user
  has_one :which_attendance, class_name: 'Message', foreign_key: 'attendance_to_change_id', dependent: :nullify

  validates :timestamp, presence: true
  validates :status, inclusion: { in: ['begin', 'finish', 'modification_request', 'settled', 'unsettled'],
                                  message: "%{value} is not a valid status" },
                      presence: true
  validate :valid_status_transition, if: -> { status == "begin" || status == "finish" }
  validate :valid_timestamp_transition, if: -> { status == "finish" }
  validate :time_check, if: -> { status == "modification_request" }
  
  def status_to_japanese
    case status
    when "begin"
      "出勤"
    when "finish"
      "退勤"
    when "modification_request"
      "修正依頼"
    when "settled"
      "修正済み"
    when "unsettled"
      "修正却下済み"
    else
      status
    end
  end
  
  def display_selection
    status_txt =
    "#{timestamp.strftime('%Y-%m-%d %H:%M:%S')} - #{status_to_japanese}"
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "status", "timestamp", "updated_at", "user_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["message", "user", "which_attendance"]
  end
  
  private
    def valid_status_transition
      last_significant_record = Attendance.where(user_id: user_id)
                                    .where(timestamp: ...timestamp)
                                    .where.not(status: ['modification_request', 'settled', 'unsettled'])
                                    .last

      if last_significant_record.present?
        if status == 'begin' && last_significant_record.status != 'finish'
          errors.add(:base, '出勤を連続で記録することはできません。')
        elsif status == 'finish' && last_significant_record.status != 'begin'
          errors.add(:base, '退勤を連続で記録することはできません。')
        end
      end
    end

    def valid_timestamp_transition
      last_begin = Attendance.where(user_id: user_id)
                             .where(id: ...id)
                             .where(status: "begin")
                             .last

      if timestamp < last_begin.timestamp
          errors.add(:base, '退勤は出勤の後にしてください。')
      end
    end

    def time_check
      errors.add(:base, "現在の日時より遅い日時は選択できません。") unless timestamp < Time.now
    end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  include AttendancesHelper
  before_action :logged_in_user
  before_action :admin_user, only: [:index, :destroy]
  
  def new
    @attendance = Attendance.new()
    @attendance.build_message
    @unread_messages = Message.where(receiver_id: current_user.id)
                              .where(attendance_id: previous_attendance(current_user)&.id..)
  end

  def index
    @q = Attendance.where(status: "begin").ransack(params[:q])
    @attendances = Kaminari.paginate_array(@q.result).page(params[:page])
  end

  def create
    @attendance = current_user.attendances.build(post_params)
    if @attendance.save
      flash[:success] = "打刻しました。"
      redirect_to new_attendance_path
    else
      flash.now[:error] = "打刻に失敗しました。"
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @attendance = Attendance.find(params[:id])
    ActiveRecord::Base.transaction do
      # 変更対象のAttendance情報を取得
      attendance_to_change = @attendance.message.attendance_to_change
      
      # 変更対象のAttendanceのtimestampを現在のAttendanceのtimestampに更新
      attendance_to_change.update!(timestamp: @attendance.timestamp)
      
      # 修正依頼statusを"settled"に更新
      @attendance.update!(status: "settled")
      
      # 修正依頼のattendance_to_change_idをnilに更新
      @attendance.message.update!(attendance_to_change_id: nil)
    end

    redirect_to attendances_path, notice: "正常に修正しました。"
    rescue ActiveRecord::RecordInvalid => e
      flash[:error] = e.message
      redirect_to attendances_path
  end

  def destroy
    @attendance = Attendance.find(params[:id])
    @attendance.update!(status: "unsettled")
    redirect_to attendances_path, notice: "正常に不許可登録が完了しました。"
    rescue ActiveRecord::RecordInvalid => e
      flash[:error]
      redirect_to attendances_path
  end

  def show
    attendance = Attendance.find(params[:id])
  end

  def previous_timestamp
    attendance = Attendance.find(params[:id]).timestamp
  end
  
  private

    def post_params
      params.require(:attendance).permit(:timestamp, :status, message_attributes: [:receiver_id, :content, :attendance_to_change_id])
    end

    #before_action
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url, status: :see_other
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url, status: :see_other) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url, status: :see_other) unless current_user&.admin?
    end

end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def previous_attendance(user)
    user.attendances.where(status: 'begin').last
  end

  def previous_status(user)
    last_attendance = user.attendances.where(status: ['begin', 'finish']).last
    last_attendance&.status
  end
end

app/views/attendances/_attendance.html.erb
<th><%= attendance.user.employee_number %></th>
<th><%= attendance.user.name %></th>

<th>
    <%= attendance.timestamp.strftime("%m月%d日 %H:%M") %>
  ~
    <% finish_record = Attendance.where(user_id: attendance.user_id)
                                  .where(timestamp: attendance.timestamp...)
                                  .where(status: "finish")
                                  .first %>
    <%= finish_record&.timestamp&.strftime("%m月%d日 %H:%M") %>
</th>

<% if (messages_for_begin = Message.where(attendance_to_change_id: attendance.id).first) && (messages_for_begin&.attendance&.status == "modification_request") %>
  <th>
      <%= messages_for_begin.attendance_to_change.timestamp.strftime("%m月%d日 %H:%M") %>
      →<%= messages_for_begin.attendance.timestamp.strftime("%m月%d日 %H:%M") %>
  </th>

  <th>
    <%= messages_for_begin&.content %>
  </th>
  <th>
    <%= button_to "許可", messages_for_begin&.attendance, data: { turbo_method: :patch,
                                    turbo_confirm: "本当に許可しますか" } %>
    <%= link_to "不許可", messages_for_begin&.attendance, class: "button", data: { turbo_method: :delete,
                                    turbo_confirm: "本当に許可しませんか" } %>
  </th>
<% else %>
  <th></th>
  <th></th>
  <th></th>
<% end %>


<% if finish_record %>
  <% if (messages_for_finish = Message.where(attendance_to_change_id: finish_record.id).first) && (messages_for_finish&.attendance&.status == "modification_request") %>
    <th>
          <%= messages_for_finish.attendance_to_change.timestamp.strftime("%m月%d日 %H:%M") %>
          →<%= messages_for_finish.attendance&.timestamp.strftime("%m月%d日 %H:%M") %>
    </th>

    <th>
      <%= messages_for_finish&.content %>
    </th>

    <th>
      <%= button_to "許可", messages_for_finish&.attendance, data: { turbo_method: :patch,
                                      turbo_confirm: "本当に許可しますか" } %>
      <%= link_to "不許可", messages_for_finish&.attendance, class: "button", data: { turbo_method: :delete,
                                      turbo_confirm: "本当に許可しませんか" } %>
    </th>
  <% else %>
    <th></th>
    <th></th>
    <th></th>
  <% end %>
<% else %>
  <th></th>
  <th></th>
  <th></th>
<% end %>

app/views/attendances/_begin_popup.html.erb
<section class="form">
  <button class="close-modal">×</button>
  <%= form_with(model: @attendance, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.hidden_field :status, value: "begin" %>

    打刻する時刻: <span id="begin_time"></span>
    <%= f.hidden_field :timestamp, id: "attendance_begin_at" %>

    
    <% if @unread_messages &.any? %>
      <p>未読メッセージ:</p>
      <% @unread_messages.each do |message| %>
        <%= message.user.name %>さん: <%= message.content %><br>
      <% end %>
    <% else %>
      <p>未読メッセージはありません。</p>
    <% end %>
    <%= f.submit "出勤", class: "btn btn-primary" %>
  <% end %>
</section>

app/views/attendances/_finish_popup.html.erb
<section class="form">
  <button class="close-modal">×</button>
  <%= bootstrap_form_with(model: @attendance, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.hidden_field :status, value: "finish" %>

      打刻する時刻: <span id="finish_time"></span>
      <%= f.hidden_field :timestamp, value: Time.current.strftime("%Y-%m-%d %H:%M:%S") %>

    <%= f.fields_for :message do |m| %>
      <div class="field">
        <%= m.collection_select :receiver_id, User.all, :id, :name, prompt: '選択してください', label: "メッセージ送り先" %>
        <%= m.text_area :content, label: "メッセージ内容" %>
      </div>
    <% end %>

    <%= f.submit "退勤登録", class: "btn btn-primary" %>
  <% end %>
</section>

app/views/attendances/_modification_popup.html.erb
<section class="form">
  <button class="close-modal">×</button>
  <%= bootstrap_form_with(model: @attendance, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.hidden_field :status, value: "modification_request" %>
    
    <%= f.fields_for :message do |m| %>
      <%= m.collection_select :attendance_to_change_id, current_user.attendances.where.not(status: ["settled", "unsettled"]), :id, :display_selection, prompt: '選択してください', label: "修正する記録:" %>
    <% end %>

    <%= f.datetime_field :timestamp, id: "attendance_timestamp", label: "修正後の時刻:", value: Time.now.strftime('%Y-%m-%dT%T') %>

    <%= f.fields_for :message do |m| %>
      <div class="field"> 
        <%= m.collection_select :receiver_id, User.all.where(admin: true), :id, :name, prompt: '選択してください', label: "修正依頼先:" %>
        <%= m.text_area :content, label: "修正理由" %>
      </div>
    <% end %>

    <%= f.submit "修正依頼", class: "btn btn-primary" %>
  <% end %>
</section>

app/views/attendances/index.html.erb
<% provide(:title, '出勤一覧') %>
<%= link_to new_user_path, class: "new_link" do %>
  <%= image_tag "signin.svg" %>
  新規登録
<% end %>
<%= link_to "社員一覧", users_path, class: "button right" %>
<%= link_to "出勤登録", new_attendance_path, class: "button right low" %>

<%= search_form_for @q, html: { data: { turbo_frame: "attendances-list" } } do |f| %>
  <% if params[:q] %>
    <%= f.label :user_name_cont, "氏名で調べる" %>
    <%= f.search_field :user_name_cont, placeholder: "氏名を入力", value: params[:q][:user_name_cont] %>
    <%= f.hidden_field :status_eq, value: "begin" %>
    <%= f.label :timestamp_gteq, "出勤日で調べる" %>
    <div class="date_range">
      <%= f.date_field :timestamp_gteq, value: params[:q][:timestamp_gteq] %>
      〜
      <%= f.date_field :timestamp_lteq_end_of_day, value: params[:q][:timestamp_lteq_end_of_day] %>
    </div>
  <% else %>
    <%= f.label :user_name_cont, "氏名で調べる" %>
    <%= f.search_field :user_name_cont, placeholder: "氏名を入力" %>
    <%= f.hidden_field :status_eq, value: "begin" %>
    <%= f.label :timestamp_gteq, "出勤日で調べる" %>
    <div class="date_range">
      <%= f.date_field :timestamp_gteq, value: Time.zone.today %>
      〜
      <%= f.date_field :timestamp_lteq_end_of_day, value: Time.zone.today %>
    </div>
  <% end %>
  <%= f.submit %>
  <%= link_to "クリア", attendances_path, class: "button" %>
<% end %>

<table id="attendances">
  <tr>
    <th>社員番号</th>
    <th>社員名</th>
    <th>出勤時間~退勤時間</th>
    <th>出勤時間修正依頼</th>
    <th>修正依頼理由</th>
    <th></th>
    <th>退勤時間修正依頼</th>
    <th>修正依頼理由</th>
    <th></th>
  </tr>
  <% @attendances.each do |attendance| %>
    <tr>
    <%= render attendance %>
    </tr>
  <% end %>
</table>

<%= paginate @attendances %>

app/views/attendances/new.html.erb
<body id="new_attendance">
  <div class="btn-wrapper">
    <button id="begin_button" class="attendance_button <%= 'disabled' if previous_status(current_user) == "begin" %>">出勤</button>
    <button id="finish_button" class="attendance_button <%= 'disabled' if previous_status(current_user) != "begin" %>">退勤</button>
  </div>
  <button id="modification_button" class="attendance_button">修正依頼</button>
  <% if current_user.admin? %>
    <%= link_to "管理者用ページ",users_path %>
  <% end %>

  <div id="modal_overlay" class="modal-overlay"></div>

  <div id="begin_modal" class="modal">
    <%= render 'begin_popup' %>
  </div>

  <div id="finish_modal" class="modal">
    <%= render 'finish_popup' %>
  </div>

  <div id="modification_modal" class="modal">
    <%= render 'modification_popup' %>
  </div>
</body>